# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceLabUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 768)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 224, 768))
        self.widget.setObjectName("widget")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setGeometry(QtCore.QRect(0, 100, 224, 668))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(18)
        item.setFont(font)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setKerning(False)
        item.setFont(font)
        self.listWidget.addItem(item)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(60, 30, 111, 41))
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(224, 0, 800, 768))
        self.stackedWidget.setAutoFillBackground(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(410, 400, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(240, 160, 450, 450))
        self.label_6.setAutoFillBackground(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(20, 210, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.spinBox = QtWidgets.QSpinBox(self.page)
        self.spinBox.setGeometry(QtCore.QRect(50, 260, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(50, 470, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(500, 250, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(440, 50, 300, 300))
        self.label_8.setAutoFillBackground(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(80, 420, 300, 300))
        self.label_9.setAutoFillBackground(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setGeometry(QtCore.QRect(440, 420, 300, 300))
        self.label_10.setAutoFillBackground(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page_3)
        self.label_11.setGeometry(QtCore.QRect(80, 30, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setGeometry(QtCore.QRect(80, 170, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.comboBox = QtWidgets.QComboBox(self.page_3)
        self.comboBox.setGeometry(QtCore.QRect(30, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.spinBox_2 = QtWidgets.QSpinBox(self.page_3)
        self.spinBox_2.setGeometry(QtCore.QRect(140, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setObjectName("spinBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 80, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 220, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.spinBox_3 = QtWidgets.QSpinBox(self.page_3)
        self.spinBox_3.setGeometry(QtCore.QRect(140, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setObjectName("spinBox_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 320, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox_2 = QtWidgets.QComboBox(self.page_3)
        self.comboBox_2.setGeometry(QtCore.QRect(30, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setGeometry(QtCore.QRect(490, 290, 72, 15))
        self.label_5.setObjectName("label_5")
        self.label_13 = QtWidgets.QLabel(self.page_4)
        self.label_13.setGeometry(QtCore.QRect(80, 170, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.spinBox_4 = QtWidgets.QSpinBox(self.page_4)
        self.spinBox_4.setGeometry(QtCore.QRect(140, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_14 = QtWidgets.QLabel(self.page_4)
        self.label_14.setGeometry(QtCore.QRect(440, 50, 300, 300))
        self.label_14.setAutoFillBackground(True)
        self.label_14.setObjectName("label_14")
        self.comboBox_3 = QtWidgets.QComboBox(self.page_4)
        self.comboBox_3.setGeometry(QtCore.QRect(30, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.spinBox_5 = QtWidgets.QSpinBox(self.page_4)
        self.spinBox_5.setGeometry(QtCore.QRect(140, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spinBox_5.setFont(font)
        self.spinBox_5.setObjectName("spinBox_5")
        self.label_15 = QtWidgets.QLabel(self.page_4)
        self.label_15.setGeometry(QtCore.QRect(80, 30, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_4)
        self.label_16.setGeometry(QtCore.QRect(440, 420, 300, 300))
        self.label_16.setAutoFillBackground(True)
        self.label_16.setObjectName("label_16")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_5.setGeometry(QtCore.QRect(100, 320, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_6.setGeometry(QtCore.QRect(260, 220, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_17 = QtWidgets.QLabel(self.page_4)
        self.label_17.setGeometry(QtCore.QRect(80, 420, 300, 300))
        self.label_17.setAutoFillBackground(True)
        self.label_17.setObjectName("label_17")
        self.comboBox_4 = QtWidgets.QComboBox(self.page_4)
        self.comboBox_4.setGeometry(QtCore.QRect(30, 240, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_7.setGeometry(QtCore.QRect(260, 80, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.stackedWidget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(350, 340, 72, 15))
        self.label_2.setObjectName("label_2")
        self.comboBox_5 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_5.setGeometry(QtCore.QRect(20, 150, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(240, 160, 450, 450))
        self.label_18.setAutoFillBackground(True)
        self.label_18.setObjectName("label_18")
        self.spinBox_6 = QtWidgets.QSpinBox(self.page_2)
        self.spinBox_6.setGeometry(QtCore.QRect(120, 150, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spinBox_6.setFont(font)
        self.spinBox_6.setObjectName("spinBox_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 550, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalSlider_age = QtWidgets.QSlider(self.page_2)
        self.horizontalSlider_age.setGeometry(QtCore.QRect(40, 240, 160, 22))
        self.horizontalSlider_age.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_age.setObjectName("horizontalSlider_age")
        self.horizontalSlider_gender = QtWidgets.QSlider(self.page_2)
        self.horizontalSlider_gender.setGeometry(QtCore.QRect(40, 320, 160, 22))
        self.horizontalSlider_gender.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_gender.setObjectName("horizontalSlider_gender")
        self.horizontalSlider_smile = QtWidgets.QSlider(self.page_2)
        self.horizontalSlider_smile.setGeometry(QtCore.QRect(40, 400, 160, 22))
        self.horizontalSlider_smile.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_smile.setObjectName("horizontalSlider_smile")
        self.horizontalSlider_pose = QtWidgets.QSlider(self.page_2)
        self.horizontalSlider_pose.setGeometry(QtCore.QRect(40, 480, 160, 22))
        self.horizontalSlider_pose.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pose.setObjectName("horizontalSlider_pose")
        self.label_19 = QtWidgets.QLabel(self.page_2)
        self.label_19.setGeometry(QtCore.QRect(100, 220, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(self.page_2)
        self.label_21.setGeometry(QtCore.QRect(100, 300, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.page_2)
        self.label_22.setGeometry(QtCore.QRect(100, 380, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_2)
        self.label_23.setGeometry(QtCore.QRect(100, 460, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(3)
        self.listWidget.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "随机人像"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "人像混合"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "人像过渡"))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", "人像编辑"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form", "FaceLab标志"))
        self.label_3.setText(_translate("Form", "1"))
        self.label_6.setText(_translate("Form", "图片：450x450"))
        self.label_7.setText(_translate("Form", "设置随机种子："))
        self.pushButton.setText(_translate("Form", "一键生成"))
        self.label_4.setText(_translate("Form", "2"))
        self.label_8.setText(_translate("Form", "TextLabel"))
        self.label_9.setText(_translate("Form", "TextLabel"))
        self.label_10.setText(_translate("Form", "TextLabel"))
        self.label_11.setText(_translate("Form", "图像1："))
        self.label_12.setText(_translate("Form", "图像2："))
        self.comboBox.setItemText(0, _translate("Form", "随机"))
        self.comboBox.setItemText(1, _translate("Form", "鲁迅"))
        self.comboBox.setItemText(2, _translate("Form", "雷军"))
        self.comboBox.setItemText(3, _translate("Form", "刘德华"))
        self.comboBox.setItemText(4, _translate("Form", "马云"))
        self.comboBox.setItemText(5, _translate("Form", "黄晓明"))
        self.comboBox.setItemText(6, _translate("Form", "杨颖"))
        self.comboBox.setItemText(7, _translate("Form", "安吉丽娜朱莉"))
        self.comboBox.setItemText(8, _translate("Form", "C罗"))
        self.comboBox.setItemText(9, _translate("Form", "特朗普"))
        self.comboBox.setItemText(10, _translate("Form", "范冰冰"))
        self.comboBox.setItemText(11, _translate("Form", "高圆圆"))
        self.comboBox.setItemText(12, _translate("Form", "莱昂纳多"))
        self.comboBox.setItemText(13, _translate("Form", "鹿晗"))
        self.comboBox.setItemText(14, _translate("Form", "玛丽莲梦露"))
        self.comboBox.setItemText(15, _translate("Form", "普京"))
        self.comboBox.setItemText(16, _translate("Form", "乔布斯"))
        self.comboBox.setItemText(17, _translate("Form", "吴亦凡"))
        self.comboBox.setItemText(18, _translate("Form", "杨幂"))
        self.comboBox.setItemText(19, _translate("Form", "基努里维斯"))
        self.pushButton_2.setText(_translate("Form", "一键生成"))
        self.pushButton_3.setText(_translate("Form", "一键生成"))
        self.pushButton_4.setText(_translate("Form", "一键生成混合图像"))
        self.comboBox_2.setItemText(0, _translate("Form", "随机"))
        self.comboBox_2.setItemText(1, _translate("Form", "鲁迅"))
        self.comboBox_2.setItemText(2, _translate("Form", "雷军"))
        self.comboBox_2.setItemText(3, _translate("Form", "刘德华"))
        self.comboBox_2.setItemText(4, _translate("Form", "马云"))
        self.comboBox_2.setItemText(5, _translate("Form", "黄晓明"))
        self.comboBox_2.setItemText(6, _translate("Form", "杨颖"))
        self.comboBox_2.setItemText(7, _translate("Form", "安吉丽娜朱莉"))
        self.comboBox_2.setItemText(8, _translate("Form", "C罗"))
        self.comboBox_2.setItemText(9, _translate("Form", "特朗普"))
        self.comboBox_2.setItemText(10, _translate("Form", "范冰冰"))
        self.comboBox_2.setItemText(11, _translate("Form", "高圆圆"))
        self.comboBox_2.setItemText(12, _translate("Form", "莱昂纳多"))
        self.comboBox_2.setItemText(13, _translate("Form", "鹿晗"))
        self.comboBox_2.setItemText(14, _translate("Form", "玛丽莲梦露"))
        self.comboBox_2.setItemText(15, _translate("Form", "普京"))
        self.comboBox_2.setItemText(16, _translate("Form", "乔布斯"))
        self.comboBox_2.setItemText(17, _translate("Form", "吴亦凡"))
        self.comboBox_2.setItemText(18, _translate("Form", "杨幂"))
        self.comboBox_2.setItemText(19, _translate("Form", "基努里维斯"))
        self.label_5.setText(_translate("Form", "3"))
        self.label_13.setText(_translate("Form", "图像2："))
        self.label_14.setText(_translate("Form", "TextLabel"))
        self.comboBox_3.setItemText(0, _translate("Form", "随机"))
        self.comboBox_3.setItemText(1, _translate("Form", "鲁迅"))
        self.comboBox_3.setItemText(2, _translate("Form", "雷军"))
        self.comboBox_3.setItemText(3, _translate("Form", "刘德华"))
        self.comboBox_3.setItemText(4, _translate("Form", "马云"))
        self.comboBox_3.setItemText(5, _translate("Form", "黄晓明"))
        self.comboBox_3.setItemText(6, _translate("Form", "杨颖"))
        self.comboBox_3.setItemText(7, _translate("Form", "安吉丽娜朱莉"))
        self.comboBox_3.setItemText(8, _translate("Form", "C罗"))
        self.comboBox_3.setItemText(9, _translate("Form", "特朗普"))
        self.comboBox_3.setItemText(10, _translate("Form", "范冰冰"))
        self.comboBox_3.setItemText(11, _translate("Form", "高圆圆"))
        self.comboBox_3.setItemText(12, _translate("Form", "莱昂纳多"))
        self.comboBox_3.setItemText(13, _translate("Form", "鹿晗"))
        self.comboBox_3.setItemText(14, _translate("Form", "玛丽莲梦露"))
        self.comboBox_3.setItemText(15, _translate("Form", "普京"))
        self.comboBox_3.setItemText(16, _translate("Form", "乔布斯"))
        self.comboBox_3.setItemText(17, _translate("Form", "吴亦凡"))
        self.comboBox_3.setItemText(18, _translate("Form", "杨幂"))
        self.comboBox_3.setItemText(19, _translate("Form", "基努里维斯"))
        self.label_15.setText(_translate("Form", "图像1："))
        self.label_16.setText(_translate("Form", "TextLabel"))
        self.pushButton_5.setText(_translate("Form", "一键生成过渡GIF"))
        self.pushButton_6.setText(_translate("Form", "一键生成"))
        self.label_17.setText(_translate("Form", "TextLabel"))
        self.comboBox_4.setItemText(0, _translate("Form", "随机"))
        self.comboBox_4.setItemText(1, _translate("Form", "鲁迅"))
        self.comboBox_4.setItemText(2, _translate("Form", "雷军"))
        self.comboBox_4.setItemText(3, _translate("Form", "刘德华"))
        self.comboBox_4.setItemText(4, _translate("Form", "马云"))
        self.comboBox_4.setItemText(5, _translate("Form", "黄晓明"))
        self.comboBox_4.setItemText(6, _translate("Form", "杨颖"))
        self.comboBox_4.setItemText(7, _translate("Form", "安吉丽娜朱莉"))
        self.comboBox_4.setItemText(8, _translate("Form", "C罗"))
        self.comboBox_4.setItemText(9, _translate("Form", "特朗普"))
        self.comboBox_4.setItemText(10, _translate("Form", "范冰冰"))
        self.comboBox_4.setItemText(11, _translate("Form", "高圆圆"))
        self.comboBox_4.setItemText(12, _translate("Form", "莱昂纳多"))
        self.comboBox_4.setItemText(13, _translate("Form", "鹿晗"))
        self.comboBox_4.setItemText(14, _translate("Form", "玛丽莲梦露"))
        self.comboBox_4.setItemText(15, _translate("Form", "普京"))
        self.comboBox_4.setItemText(16, _translate("Form", "乔布斯"))
        self.comboBox_4.setItemText(17, _translate("Form", "吴亦凡"))
        self.comboBox_4.setItemText(18, _translate("Form", "杨幂"))
        self.comboBox_4.setItemText(19, _translate("Form", "基努里维斯"))
        self.pushButton_7.setText(_translate("Form", "一键生成"))
        self.label_2.setText(_translate("Form", "4"))
        self.comboBox_5.setItemText(0, _translate("Form", "随机"))
        self.comboBox_5.setItemText(1, _translate("Form", "鲁迅"))
        self.comboBox_5.setItemText(2, _translate("Form", "雷军"))
        self.comboBox_5.setItemText(3, _translate("Form", "刘德华"))
        self.comboBox_5.setItemText(4, _translate("Form", "马云"))
        self.comboBox_5.setItemText(5, _translate("Form", "黄晓明"))
        self.comboBox_5.setItemText(6, _translate("Form", "杨颖"))
        self.comboBox_5.setItemText(7, _translate("Form", "安吉丽娜朱莉"))
        self.comboBox_5.setItemText(8, _translate("Form", "C罗"))
        self.comboBox_5.setItemText(9, _translate("Form", "特朗普"))
        self.comboBox_5.setItemText(10, _translate("Form", "范冰冰"))
        self.comboBox_5.setItemText(11, _translate("Form", "高圆圆"))
        self.comboBox_5.setItemText(12, _translate("Form", "莱昂纳多"))
        self.comboBox_5.setItemText(13, _translate("Form", "鹿晗"))
        self.comboBox_5.setItemText(14, _translate("Form", "玛丽莲梦露"))
        self.comboBox_5.setItemText(15, _translate("Form", "普京"))
        self.comboBox_5.setItemText(16, _translate("Form", "乔布斯"))
        self.comboBox_5.setItemText(17, _translate("Form", "吴亦凡"))
        self.comboBox_5.setItemText(18, _translate("Form", "杨幂"))
        self.comboBox_5.setItemText(19, _translate("Form", "基努里维斯"))
        self.label_18.setText(_translate("Form", "TextLabel"))
        self.pushButton_8.setText(_translate("Form", "一键生成"))
        self.label_19.setText(_translate("Form", "年龄"))
        self.label_21.setText(_translate("Form", "性别"))
        self.label_22.setText(_translate("Form", "微笑"))
        self.label_23.setText(_translate("Form", "姿势"))
